GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};

CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL
);

GRANT ALL PRIVILEGES ON TABLE users TO ${DB_USER};

CREATE TABLE IF NOT EXISTS "signed-users" (
	id INTEGER PRIMARY KEY REFERENCES users(id),
	name TEXT NOT NULL,
	username TEXT NOT NULL,
	password TEXT
);

GRANT ALL PRIVILEGES ON TABLE "signed-users" TO ${DB_USER};
-- VARCHAR(n) -> TEXT de taille max n

CREATE TYPE game_state AS ENUM ('RUNNING', 'PAUSE', 'OVER');

CREATE TABLE IF NOT EXISTS games (
	id INTEGER PRIMARY KEY,
	p1_id INTEGER REFERENCES users(id),
	p2_id INTEGER REFERENCES users(id),
	state game_state NOT NULL DEFAULT 'RUNNING',
	p1_score INT DEFAULT 0,
  	p2_score INT DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
GRANT ALL PRIVILEGES ON TABLE games TO ${DB_USER};