DO $$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DB_USER}') THEN
      CREATE ROLE ${DB_USER} WITH LOGIN PASSWORD '${DB_PASS}';
   END IF;
END;
$$ LANGUAGE plpgsql;

GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};

-- VARCHAR(n) -> TEXT de taille max n
