CREATE OR REPLACE FUNCTION get_game_history(
	_id INTEGER,
)
RETURNS TABLE(success BOOLEAN, msg TEXT,  INTEGER) AS $$
DECLARE
	_p1_bot BOOLEAN NOT NULL := FALSE;
	_p2_bot BOOLEAN NOT NULL := FALSE;
	_type game_type NOT NULL := 'VS';
	_new_game_id INTEGER;
BEGIN
	
	
EXCEPTION
	WHEN OTHERS THEN
		RETURN QUERY SELECT FALSE, SQLERRM, NULL::INTEGER;
END;
$$ LANGUAGE plpgsql;


