CREATE TABLE IF NOT EXISTS channels_users (
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	channel_id INTEGER NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
	operator BOOLEAN NOT NULL DEFAULT FALSE, 
	joined_at TIMESTAMP DEFAULT NOW(),
	banned BOOLEAN NOT NULL DEFAULT FALSE,
	left_channel BOOLEAN NOT NULL DEFAULT FALSE
);
